language: android
android:
  components:
    - android-28
    - build-tools-28.0.3
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_install:
        - sdkmanager --update && yes | sdkmanager --licenses && yes
        - echo “y” | /opt/android/sdk/tools/bin/sdkmanager “build-tools;26.0.2”
        - chmod +x gradlew
        - touch local.properties
branches:
        only:
                - master
