language: android
android:
  components:
    - android-28
    - build-tools-28.0.3
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_install:
        - sdkmanager --update && yes | sdkmanager --licenses && yes
        - yes | sdkmanager "platforms;android-28.0.3"
        - echo yes | sdkmanager "tools"
        - echo yes | sdkmanager "platforms;android-27" # Latest platform required by SDK tools
        - echo yes | sdkmanager "extras;android;m2repository"
        - echo yes | sdkmanager "extras;google;m2repository"
        - echo yes | "Accept? (y/N):"
        - chmod +x gradlew
        - touch local.properties  
branches:
        only:
                - master
