language: android
android:
  components:
    - android-28
    - build-tools-28.0.3
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_install:
        - sdkmanager --update && yes | sdkmanager --licenses
        - echo “Y”
        - chmod +x gradlew
        - touch local.properties
branches:
        only:
                - master
