language: android
android:
  components:
    - android-28
    - build-tools-28.0.3
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_install:
        - sdkmanager --update && yes | sdkmanager --licenses && yes
        - run: sdkmanager --install "ndk-bundle" && yes | sdkmanager --licenses
        - echo “y”
        - chmod +x gradlew
        - echo “y”
        - touch local.properties
        - echo “y”
branches:
        only:
                - master
