language: android
android:
  components:
    - tools
    - android-27
    - build-tools-27.0.1
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
env:
 global:
 - ANDROID_API=27
 - ANDROID_BUILD_TOOLS=27.0.1

before_install:
        - chmod +x gradlew
        - yes | sdkmanager --licenses
        - touch local.properties  
branches:
        only:
                - master
